# POST  http://localhost:8080/api/users/create
# Content-Type: application/json

# {
#     "username" : "Tran Trung Tien",
#     "email" : "tien@gmail.com",
#     "password" : "12345"
# }

# GET  http://localhost:8080/api/users/61911ea010aebb395263c7b4
# Content-Type: application/json


# POST  http://localhost:8080/api/conversations/61926fcb7e2b5864670ee0bb
# Content-Type: application/json

# {
#     "conversationName" : "Learn_Phuong Anh"
# }


# PATCH http://localhost:8080/api/users/update/619df6b936fa350c5cf162e0
# Content-Type: application/json

# {
#     "newConversation" : "619ca03b1b30d742ba1587a1"
# }


# PATCH http://localhost:8080/api/conversations/add_new_user/619ca03b1b30d742ba1587a1
# Content-Type: application/json

# {
#     "newUser" : "619df6b936fa350c5cf162e0"
# }


# GET http://localhost:8080/api/conversations/read_all_member/61926fcb7e2b5864670ee0bb
# Content-Type: application/json


# POST  http://localhost:8080/api/messages/619270d59ede19af14a42339/61926ff57e2b5864670ee0bd
# Content-Type: application/json

# {
#     "content" : "Yeah Its me What's up !!!!!", 
#     "reply_user_id" : "61926fcb7e2b5864670ee0bb"
# }



# GET  http://localhost:8080/api/messages/619270d59ede19af14a42339/61926ff57e2b5864670ee0bd
# Content-Type: application/json



# POST  http://localhost:8080/api/attachments/619380da34a43492cf2bf5d2
# Content-Type: application/json

# PUT  http://localhost:8080/api/attachments/619380da34a43492cf2bf5d2
# Content-Type: application/json


GET  http://localhost:8080/api/messages/619ca03b1b30d742ba1587a1/25/2021-11-29T02:19:56.779Z
Content-Type: application/json




